"""Added password_hash field in user table

Revision ID: 12aaf2c9f5f8
Revises: 4703218b1f40
Create Date: 2020-07-06 00:53:16.959266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12aaf2c9f5f8'
down_revision = '4703218b1f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=124), nullable=True))
    op.create_index(op.f('ix_user_password_hash'), 'user', ['password_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_password_hash'), table_name='user')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
