"""post table

Revision ID: 368cd37d6b05
Revises: d9337ff0fef7
Create Date: 2020-07-08 10:43:24.872231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368cd37d6b05'
down_revision = 'd9337ff0fef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    # ### end Alembic commands ###
