"""User table

Revision ID: ab451d001f83
Revises: cbc14b62a612
Create Date: 2020-07-17 16:09:17.859254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab451d001f83'
down_revision = 'cbc14b62a612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('facebook_url', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('linkedin_url', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('twitter_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'twitter_url')
    op.drop_column('user', 'linkedin_url')
    op.drop_column('user', 'facebook_url')
    # ### end Alembic commands ###
