"""Sermon Table

Revision ID: cba323888411
Revises: 368cd37d6b05
Create Date: 2020-07-15 01:49:41.625331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba323888411'
down_revision = '368cd37d6b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sermon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=124), nullable=True),
    sa.Column('text', sa.String(length=124), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sermon_created_at'), 'sermon', ['created_at'], unique=False)
    op.create_index(op.f('ix_sermon_text'), 'sermon', ['text'], unique=False)
    op.create_index(op.f('ix_sermon_title'), 'sermon', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sermon_title'), table_name='sermon')
    op.drop_index(op.f('ix_sermon_text'), table_name='sermon')
    op.drop_index(op.f('ix_sermon_created_at'), table_name='sermon')
    op.drop_table('sermon')
    # ### end Alembic commands ###
