"""Sermon 

Revision ID: cbc14b62a612
Revises: cba323888411
Create Date: 2020-07-15 02:46:56.992872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc14b62a612'
down_revision = 'cba323888411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sermon', sa.Column('body', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_sermon_body'), 'sermon', ['body'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sermon_body'), table_name='sermon')
    op.drop_column('sermon', 'body')
    # ### end Alembic commands ###
